(() => {
  const tokenKey = 'bdoffer_admin_token';
  const $ = (selector) => document.querySelector(selector);
  const setStatus = (node, message, type = '') => { node.textContent = message; node.className = `status ${type}`; };
  const api = async (path, options = {}) => { const headers = { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(sessionStorage.getItem(tokenKey) ? { Authorization: `Bearer ${sessionStorage.getItem(tokenKey)}` } : {}), ...(options.headers || {}) }; const response = await fetch(`${path}${path.includes('?') ? '&' : '?'}ts=${Date.now()}`, { ...options, headers, cache: 'no-store', credentials: 'include' }); const data = await response.json().catch(() => null); if (!response.ok || !data) throw new Error(data?.error || 'backend_error'); return data; };
  const loginCard = $('#login-card'), dashboard = $('#dashboard'), logout = $('#logout'), loginStatus = $('#login-status'), dashStatus = $('#dashboard-status');
  const validHttps = (value) => { try { const url = new URL(value); return url.protocol === 'https:' && Boolean(url.hostname); } catch { return false; } };
  const renderLinks = (links) => { const root = $('#links'); root.replaceChildren(); if (!links.length) { const empty = document.createElement('p'); empty.className = 'muted'; empty.textContent = 'No affiliate links yet. Add the first one above.'; root.append(empty); return; } links.forEach(link => { const row = document.createElement('div'); row.className = 'row'; const info = document.createElement('div'); info.style.minWidth = '0'; const title = document.createElement('strong'); title.textContent = `${link.label} (${link.linkKey})`; const url = document.createElement('div'); url.className = 'url'; url.title = link.url; url.textContent = link.url; info.append(title, url); const actions = document.createElement('div'); actions.className = 'actions'; const input = document.createElement('input'); input.type = 'url'; input.value = link.url; input.setAttribute('aria-label', `${link.label} affiliate URL`); const save = document.createElement('button'); save.textContent = 'Update'; save.addEventListener('click', async () => { if (!validHttps(input.value.trim())) return setStatus(dashStatus, 'Use a valid HTTPS URL.', 'error'); save.disabled = true; try { await api(`/api/admin/links/${encodeURIComponent(link.linkKey)}`, { method: 'PUT', body: JSON.stringify({ ...link, url: input.value.trim() }) }); setStatus(dashStatus, `${link.label} updated successfully.`, 'success'); await loadLinks(); } catch (error) { setStatus(dashStatus, error.message, 'error'); } finally { save.disabled = false; } }); const remove = document.createElement('button'); remove.className = 'danger'; remove.textContent = 'Remove'; remove.addEventListener('click', async () => { if (!window.confirm(`Remove ${link.label}?`)) return; remove.disabled = true; try { await api(`/api/admin/links/${encodeURIComponent(link.linkKey)}`, { method: 'DELETE' }); setStatus(dashStatus, `${link.label} removed.`, 'success'); await loadLinks(); } catch (error) { setStatus(dashStatus, error.message, 'error'); } finally { remove.disabled = false; } }); actions.append(input, save, remove); row.append(info, actions); root.append(row); }); };
  const loadLinks = async () => { const data = await api('/api/admin/links'); renderLinks(Array.isArray(data.links) ? data.links : []); };
  const showDashboard = () => { loginCard.classList.add('hidden'); dashboard.classList.remove('hidden'); logout.hidden = false; loadLinks().catch(error => setStatus(dashStatus, error.message, 'error')); };
  $('#add-link-form').addEventListener('submit', async event => { event.preventDefault(); const form = event.target; const button = form.querySelector('button'); const values = Object.fromEntries(new FormData(form)); values.sortOrder = Number(values.sortOrder); values.isActive = true; if (!/^[a-z0-9_-]{2,50}$/.test(values.linkKey) || !validHttps(values.url)) return setStatus(dashStatus, 'Enter a unique key and valid HTTPS URL.', 'error'); button.disabled = true; try { await api('/api/admin/links', { method: 'POST', body: JSON.stringify(values) }); form.reset(); form.sortOrder.value = '50'; setStatus(dashStatus, 'Affiliate link added successfully.', 'success'); await loadLinks(); } catch (error) { setStatus(dashStatus, error.message, 'error'); } finally { button.disabled = false; } });
  $('#login-form').addEventListener('submit', async event => { event.preventDefault(); const button = event.target.querySelector('button'); button.disabled = true; try { const data = await api('/api/admin/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); sessionStorage.setItem(tokenKey, data.token); showDashboard(); } catch { setStatus(loginStatus, 'Login failed. Check your credentials.', 'error'); } finally { button.disabled = false; } });
  logout.addEventListener('click', async () => { try { await api('/api/admin/logout', { method: 'POST' }); } catch {} sessionStorage.removeItem(tokenKey); location.reload(); });
  if (sessionStorage.getItem(tokenKey)) api('/api/admin/session').then(data => data.authenticated ? showDashboard() : sessionStorage.removeItem(tokenKey)).catch(() => sessionStorage.removeItem(tokenKey));
})();
